name: 1_Outputs_wkfw
on: push

jobs:
  test_artifacts_job:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.publish1.outputs.filename }}   ## steps.<id>.outputs.<keyvalue>
    steps:
      - name: "Test Upload Artifacts"
        uses: actions/checkout@v3
      - run: echo "Hello Buddy" > /tmp/buddy.txt
      - run: df -h
      - run: mkdir -p /tmp/db
      - run: echo "Hello Nana" > /tmp/db/nana.txt
      - uses: actions/upload-artifact@v4           #Define Artifact Upload Action
        with:
          name: my_upload_artifact             #userdefined Artifact Name ;  Files and Dirs will be Uploaded to this Artifact
          path: |                                 #Files and Dirs thats are Uploading to above Artifact
              /tmp/buddy.txt
              /tmp/db/nana.txt
      - name: "Learning about outputs"
        id: publish1                            #Set ID, will refer in above outputs
        run: find /tmp/db -type f -name "nana*" -execdir echo "filename={}" >> $GITHUB_OUTPUT ';'  ## Storing KeyValue-Pair , the key "filename" used above outputs.

  output_job:
    runs-on: ubuntu-latest
    needs: test_artifacts_job
    steps:
        - name: "Displaying the Output value from previous Job"
          run: echo "${{ needs.test_artifacts_job.outputs.output1 }}""   ## needs.<jobname>.outputs.<outputname>
                           


