##Env Variables learning in Workflow.


name: 3_Env_vars_wkfw

on: push

env:                   ## Declare Env Variables at Workflow level

  DBNAME: "Oracle"
  PORT: 1551
  HOSTNAME: "test.db.oracle.com"

jobs:
  
  env_vars_job:
   
    runs-on: ubuntu-latest
    env:
      USERNAME: "Jana_user"         # Declare Env Variable in  Job level
    steps:
      - name: "Printing ENv Variables Values"
        run: echo "The DB NAme is ${DBNAME} and Port is ${PORT} and Username is ${USERNAME}"                        ## Method 1 : Printing Env Variables values
      - run: echo "The DB NAme is ${{ env.DBNAME}} and Port is ${{ env.PORT }} and Username is ${{ env.USERNAME }}"  ## Method 2 : Printing Env Variables values

      - name: "Get Code from Repo"
        uses: actions/checkout@v3

      - name: "Running Shell Script"
        run: sh 1_pass_env_values_wkfw.sh
          