### Leaning Seceres in GITHUB Actions Workflow.

name: 4_Secrets_wkfw

on: push

env:
    DB_PASSWORD={{ secret.PASSWORD_SECRET }}

jobs:
    secrets_job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The Password is ${{ env.DB_PASSWORD}} "