### Leaning Seceres in GITHUB Actions Workflow.

name: 4_Secrets_wkfw

on: push

env:
    DB_PASSWORD: ${{ secrets.PASSWORD_SECRET }}

jobs:
    secrets_job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The Password is ${{ env.DB_PASSWORD}} "

    env_repo_job:
      environment: DEV
      runs-on: ubuntu-latest
      steps:
        
        - name: " The Env is dev"
          run: echo " The DB Name is ${{ secrets.DBNAME }} "
          