### Leaning Seceres in GITHUB Actions Workflow.

name: 4_Secrets_wkfw

on: push

env:
    DB_PASSWORD: ${{ secrets.PASSWORD_SECRET }}    ##Passing Repository Secret Varibale to Env Variable

jobs:
    secrets_job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The Password is ${{ env.DB_PASSWORD}} "    ### Display Env Variable 

    env_repo_job:
      environment: DEV                     ##Declare Environment
      runs-on: ubuntu-latest
      steps:
        
        - name: " The Env is dev"
          run: echo " The DB Name is ${{ secrets.DBNAME }} "   ## Passing  Environmnet related secret
          